apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mi-cluster-eks
  region: us-east-1

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3
    iam:
      instanceRoleARN: arn:aws:iam::307946640631:role/eks-node-role
    privateNetworking: true

serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
