apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mi-cluster-eks
  region: us-east-1

vpc:
  nat:
    gateway: Single
  subnets:
    public:
      - cidr: 10.0.0.0/24
        availabilityZone: us-east-1a
      - cidr: 10.0.1.0/24
        availabilityZone: us-east-1b
    private:
      - cidr: 10.0.2.0/24
        availabilityZone: us-east-1a
      - cidr: 10.0.3.0/24
        availabilityZone: us-east-1b

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3
    iam:
      instanceRoleARN: arn:aws:iam::307946640631:role/eks-node-role
    privateNetworking: false  # Cambia esto a false para red pública

serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
